
export type Language = { 
    label: string,
    selector: "pt" | "en"
}

export type TranslateWords = "initial.message"
    | "login.title"
    | "login.message"
    | "register.title"
    | "register.message"
    | "commons.yes"
    | "commons.no"
    | "commons.ok"
    | "commons.open"
    | "commons.close"
    | "commons.exit"
    | "commons.oops"
    | "commons.success"
    | "commons.alert"
    | "commons.error"
    | "commons.search"
    | "commons.signin"
    | "commons.signup"
    | "commons.signout"
    | "commons.enter"
    | "commons.buy"
    | "commons.sell"
    | "commons.send"
    | "commons.scan"
    | "commons.receive"
    | "commons.create"
    | "commons.import"
    | "commons.add"
    | "commons.update"
    | "commons.delete"
    | "commons.save"
    | "commons.delete.account"
    | "commons.authenticate"
    | "commons.authenticate.message"
    | "commons.detectedkey"
    | "commons.nodescription"
    | "commons.copy"
    | "commons.options"
    | "commons.copied"
    | "commons.name"
    | "commons.description"
    | "commons.version"
    | "labels.username"
    | "labels.about"
    | "labels.mywebsite"
    | "labels.lnaddress"
    | "labels.friends"
    | "labels.privatekey"
    | "labels.wallet.add"
    | "labels.wallet.name"
    | "labels.wallet.getseed"
    | "menu.home"
    | "menu.buy&sell"
    | "menu.donate"
    | "menu.chats"
    | "menu.notifications"
    | "menu.setting"
    | "message.invalidkey"
    | "message.detectedkey"
    | "message.detectedkey.value"
    | "message.wallet.create" 
    | "settings.relays"
    | "settings.account.edit"
    | "settings.about"
    | "settings.about.content"
    | "settings.nostrkey.copy"
    | "settings.secretkey.copy"
    | "settings.chooselanguage"
    | "settings.security"
    | "section.title.wallets"
    | "section.title.sales"
    | "section.title.transactions"
    | "section.title.transactions.empty"
    | "section.title.frends.empty"
    | "section.title.sharefriend"
    | "section.description.sharefriend"
    | "section.title.talkdevelopers"
    | "section.description.talkdevelopers"
    | "message.wallet.alertcreate"
    | "message.wallet.notfound"
    | "message.wallet.nameempty"
    | "message.wallet.invalidseed"
    | "message.wallet.saved"
    | "message.wallet.saveseed"
    | "message.wallet.wantdelete"
    | "message.wallet.alertdelete"
    | "message.transaction.insufficient_funds"
    | "message.transaction.confirmed"
    | "message.transaction.notconfirmed"
    | "message.shortly"
    | "message.error.notaccessgallery"
    | "message.copied"
    | "message.profile.saved"
    | "message.profile.wantleave"
    | "message.profile.alertleave"
    | "message.profile.alertname"
    | "message.request.error"
    | "wallet.lightning.tag"
    | "wallet.bitcoin.tag"
    | "wallet.title.receive"
    | "wallet.title.send"
    | "wallet.title.sendvalue"
    | "wallet.title.sendfor"
    | "wallet.title.sendreceiver"
    | "wallet.title.settings"
    | "wallet.title.import"
    | "wallet.subtitle.balance"
    | "wallet.placeholder.addressuser"
    | "wallet.title.seed"
    | "screen.title.addwallet"
    | "screen.title.importwallet"
    | "screen.title.addfriend"
    | "screen.title.donate"
    | "screen.title.newchat"





    | "en"
    | "pt"



