
export type Language = "pt" | "en"

export type TranslateWords = "initial.message"
    | "login.title"
    | "login.message"
    | "register.title"
    | "register.message"
    | "commons.search"
    | "commons.signin"
    | "commons.signup"
    | "commons.signout"
    | "commons.enter"
    | "commons.buy"
    | "commons.sell"
    | "commons.send"
    | "commons.receive"
    | "commons.create"
    | "commons.update"
    | "commons.delete"
    | "commons.delete.account"
    | "commons.authenticate"
    | "commons.authenticate.message"
    | "labels.username"
    | "labels.privatekey"
    | "menu.home"
    | "menu.buy&sell"
    | "menu.donate"
    | "menu.setting"

